name: EnderChest
version: ${project.version}
main: com.legit.enderchest.EnderChest
api-version: 1.16
authors: [Legit Killer]
description: EnderChest Command plugin
commands:

  enderchest:
    aliases: [ec]
    usage: /<command>

  enderchesthelp:
    aliases: [echelp]
    usage: /<command>
